services:
  api:
    build: 
      dockerfile: Dockerfile
      context: /api
    volumes:
      - ./api:/api
      - /api/node_modules
    ports:
      - "5000:5000"
  webapp:
    build:
      dockerfile: Dockerfile
      context: /webapp
    volumes:
      - ./webapp:/webapp
      - /webapp/node_modules
    ports:
      - "3000:3000"